### ISSUE TITLE
Submission: Benchmark for testing medical AI agents in conversation

### ISSUE THREAD

**Issue by klemenvod** [AI-in-Health/MedLLMsPracticalGuide#13]
Hi! We've recently released SymptomCheck Bench, an open-source benchmark for testing diagnostic accuracy of medical AI agents in conversational settings. Would love to have it included in your collection.

Our benchmark simulates doctor-patient interactions and focuses specifically on evaluating LLM-based symptom checker applications. Unlike traditional static benchmarks, it tests the agent's ability to gather information through text conversation before making a diagnosis.

You can find more details here:

Blog: https://medask.tech/blogs/introducing-symptomcheck-bench/

GitHub: https://github.com/medaks/symptomcheck-bench

Let me know if you need any additional information.

**Comment by inFaaa** [comment]
Thanks for your awesome work. We have added your project to the Introduction of New Benchmarks section.
