### ISSUE TITLE
Invitation to Explore Our Project ClinicalAgent and Collaborate

### ISSUE THREAD

**Issue by lingyue404** [AI-in-Health/MedLLMsPracticalGuide#8]
I am excited to discover the amazing project you have developed. Please feel free to visit our previously published paper, "ClinicalAgent: Clinical Trial Multi-Agent System with Large Language Model-based Reasoning" [https://arxiv.org/abs/2404.14777], which was published on April, 2024. We look forward to your suggestions and feedback. If you have any ideas and would like to collaborate with us, you are welcome.

**Comment by AI-in-Health** [comment]
Thank you for your interesting and insightful work. We have added your paper to our repository. We look forward to your further contributions. Meanwhile, we are very open to collaboration. Therefore, similarly, please let us know if you have any ideas.
